### PR TITLE
Use numerical differentiation to check derivatives

### PR DESCRIPTION
**Pull request by sangyx**

### CODE REVIEW

**Comment by hameerabbasi** [comment]
Not a bad idea to use side-by-side to verify results, but I'd still use hardcoded derivatives as well. :)

**Comment by sangyx** [comment]
Fine. I want to provide another method to check derivatives because some gradients are too complicated.

**Comment by hameerabbasi** [comment]
We just need to check in essence:

1. Individual derivatives
2. Chain rule.

**Comment by sangyx** [comment]
OK, but I want to keep this function to quickly verify whether the program is correct.

**Comment by hameerabbasi** [comment]
That seems fine to me.

**Comment by dhirschfeld** [comment]
Just as an aside I've previously used [`numdifftools`](https://github.com/pbrod/numdifftools) which implements an adaptive method to provide more accurate numerical derivatives for validation.

**Pull request merged**
