### PR TITLE
Add tests

### LINKED ISSUE #4: Add tests
As stated in the [GSoC project ideas](https://uarray.org/en/latest/gsoc/2020/ideas.html), add some test cases for the functions computing derivatives in `_builtin_diffs.py`.

### PR DESCRIPTION
**Pull request by joaosferreira**
This is intended to resolve issue #4 with the same name. Closes #4

### CODE REVIEW

**Comment by hameerabbasi** [comment]
@joaosferreira Can you also push some example tests up to the same folder? https://docs.pytest.org/en/latest/getting-started.html

**Comment by joaosferreira** [comment]
Yes, I was thinking of using [symbolic differentiation](https://docs.sympy.org/latest/tutorial/calculus.html) to compare results. Is this okay?

**Comment by hameerabbasi** [comment]
Well, we don't have symbolic differentiation in this library. You can, of course, use that to work out the derivative and test against that on some data points, but I'd avoid using SymPy in the code directly.

**Comment by joaosferreira** [comment]
I've pushed some simple math tests for various backends. Because of difficulties installing PyTorch in my conda environment this backend hasn't yet been tested.

I've also changed the `tests` directory to comply with the project structure proposed in issue #1.

I appreciate every feedback on this so that I can create further tests for the computed derivatives.

**Comment by hameerabbasi** [comment]
This looks okay to me, except that these all seem to be tests that should go in `unumpy`, there’s nothing specific to `udiff` here. The tests Themselves are excellent and well written.

**Comment by joaosferreira** [comment]
You are right, I can open a PR there for these tests if you like.

**Comment by hameerabbasi** [comment]
That would be ideal.

**Comment by hameerabbasi** [comment]
Superseded by Quansight-Labs/unumpy#44.

**Pull request closed without merging**
