### PR TITLE
add jvp jacobian and test cases

### PR DESCRIPTION
**Pull request by sangyx**
I have split the `lambda g, ans, x, y: ` into `lambda ans, x, y: lambda g: ` and add jacobian support. While the higher-order derivative is still subject to the forward gradient calculation and falls into an infinite loop. I need more time. 
You may check the code and come up with new ideas.

### CODE REVIEW

**Comment by hameerabbasi** [comment]
Can you add a few test-cases where this fails?

**Comment by sangyx** [comment]
> Can you add a few test-cases where this fails?

You can remove the code `with ua.set_backend(numpy_backend, coerce=True):` in `JVPDiffArray.to` to see the error.

**Comment by hameerabbasi** [comment]
Thanks, that helps. I’ll fix this on Monday.

**Comment by sangyx** [comment]
Thanks! I'm trying to save the second-order derivative in another list. But it seems hard to decide when to use them.

**Comment by hameerabbasi** [comment]
Passing back to you.

> Thanks! I'm trying to save the second-order derivative in another list. But it seems hard to decide when to use them.

This isn't necessary, I think using `.to` twice is fine. 😄

**Comment by sangyx** [comment]
> Passing back to you.
> 
> > Thanks! I'm trying to save the second-order derivative in another list. But it seems hard to decide when to use them.
> 
> This isn't necessary, I think using `.to` twice is fine. 😄

OK.

**Comment by sangyx** [comment]
I need some help. I tried different methods to solve the problem of higher-order derivatives, but they all failed. Taking the second derivative as an example, **the key to the problem is how to clearly divide the `JVP` and `children` of the first and second derivatives**. There are methods and problems I tried:

1. Using a derivative method similar to `VJP`. We save the diff function in `_jvp` and the children of each node in `_children`. occurred in the process of `_forward`:

```python
def _forward(self, grad_variables, end_node, base, cn=None):
        if grad_variables is None:
            grad_variables = np.ones_like(self)

        if end_node is None:
            end_node = self

        if self._jvp:
            grad_variables = self._jvp[cn](grad_variables)

        if end_node is None or end_node.id == self.id:
            if self._diff is None:
                self._diff = {}

            if base in self._diff:
                self._diff[base] = self._diff[base] + grad_variables
            else:
                self._diff[base] = grad_variables

        # The error occurred here. Because the gradient is also registered in the process of derivation, 
        # the `_children` list is constantly expanding, falling into an infinite loop.
        if self._children:
            for cn, child in self._children:
                child._forward(grad_variables, end_node, base, cn=cn)
```

2. Then I tried to save the `JVP` and `children` in `_next` to solve the problem `infinite loop`. I add `_next_jvp` and `_next_children`. We will register diff in `_next` and replace the `_jvp` and `_children` with `_next` when we call `to`. 

```python
def _replace_next(self):
        self._jvp = self._next_jvp
        self._children = self._next_children

        if self._children:
            for cn, child in self._children:
                child._replace_next()

    def _reset_next(self):
        self._next_jvp = None
        self._next_children = None

        if self._children:
            for cn, child in self._children:
                child._reset_next()

    def to(self, x, grad_variables=None, jacobian=False):
        if jacobian:
            if self._jacobian is None or x not in self._jacobian:
                x._replace_next()
                x._reset_next()
                for position in itertools.product(
                    *[range(i) for i in np.shape(x)]
                ):
                    grad_variables = np.zeros_like(x)
                    grad_variables[position] = 1
                    x._forward_jacobian(grad_variables, self, position, x)

            old_axes = tuple(range(np.ndim(self) + np.ndim(x)))
            new_axes = old_axes[np.ndim(x) :] + old_axes[: np.ndim(x)]
            self._jacobian[x] = np.transpose(
                np.reshape(
                    np.stack(self._jacobian[x].values()),
                    np.shape(x) + np.shape(self),
                ),
                new_axes,
            )
            return self._jacobian[x]
        else:
            if self._diff is None or x not in self._diff:
                x._replace_next()
                x._reset_next()
                x._forward(grad_variables, self, x)
            return self._diff[x]
```

This way solve the problem `infinite loop`, while there is a new problem that we can only call this only once. For example, `y = np.log(x1) + x1 * x2 - np.sin(x2)`, if we call `y.to(x1)`, we will replace the `_jvp` and `_children` with `_next` in `v0`, `v2`, `v3`, `v4` and `v6`. But when we call `y.to(x2)`, their `_jvp` and `_children` will be covered by a wrong value.



To solve this problem, we need to determine when to replace it.

But I tried to use the derivable variable of `y` to determine whether it should be replaced, but this does not seem to be useful.    
In addition, I also tried to add the `parents_num` of the node to determine whether the node has been fully derivated, but there will still be problems that change continuously with the gradient registration. 

This problem seems to be getting more and more complicated, so I return to the second step and think about whether there is a concise way to decide when to replace it, but I haven't figured it out yet. Do you have any ideas or suggestions?

**Comment by hameerabbasi** [comment]
Thanks so much for the detailed description of the problem.

> Do you have any ideas or suggestions?

It seems to me generally that we're storing what should be permanent caches in class variables. Would it help if we adopted the same approach as in JVP, instead of replacing these attributes; we cache them in a `dict` with a key. That way, instead of getting replaced, they'll be stored in the `dict` for future use.

**Comment by sangyx** [comment]
It is worth trying to store all the information needed for derivation in the class. But this will waste space. I am considering whether it is necessary for us to support higher-order derivatives in `JVP` if `VJP` can already do it more easily.

**Comment by hameerabbasi** [comment]
> It is worth trying to store all the information needed for derivation in the class. But this will waste space. I am considering whether it is necessary for us to support higher-order derivatives in `JVP` if `VJP` can already do it more easily.

Maybe provide a way to clear the cache for better control?

**Comment by hameerabbasi** [comment]
Thanks, @sangyx!

**Pull request merged**
